name: Lint

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Run Black
      run: |
        black --check .
    
    - name: Run Ruff
      run: |
        ruff check .
    
    - name: Run MyPy
      run: |
        mypy commi/ tests/ --ignore-missing-imports

    - name: Verify import order
      run: |
        ruff check . --select I
