name: Test xclip on Linux

on:
    push:
      branches: [ '*' ]
    pull_request:
      branches: [ '*' ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xclip
        run: |
          if ! command -v xclip &>/dev/null; then
            sudo apt-get update
            sudo apt-get install -y xclip
          fi
          xclip -version || echo "xclip installed successfully"
