name: Build and Test on macOS

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python3 -m ensurepip --default-pip
          python3 -m pip install --upgrade pip poetry

      - name: Verify Poetry installation
        run: poetry --version

      - name: Build the package
        run: chmod +x ./build.sh && ./build.sh

      - name: Verify executable
        run: |
          export TERM=xterm  # Set a default terminal
          if ! command -v commi &>/dev/null; then
            echo "Error: commi executable was not found!"
            exit 1
          fi
          echo "Commi executable found, running a test..."
          commi --help || { echo "Error: Executable failed to run!"; exit 1; }
